### ISSUE TITLE
Add Harmony Support

### ISSUE THREAD

**Issue by bohendo** [degenfolio/degenfolio#2]
**Tasks**
- [ ] find (covalent?) endpoint that gives ONE transfers (or hashes) to/from some address
- [ ] find (covalent?) endpoint that gives token transfers (or hashes) to/from some address
- [ ] find (covalent?) endpoint that gives internal ONE transfers (or hashes) to/from some address (bonus)
- [ ] find (covalent?) endpoint that gives full tx details for some hash
- [ ] use above endpoints to implement `syncAddressBook: (addressBook: AddressBook) => Promise<void>` function that syncs harmony data for an address book. See [AddressBook type](https://github.com/bohendo/valuemachine/blob/main/modules/types/src/addressBook.ts#L64)
- [ ] find example tx hashes for each action
- [ ] write test for what you expect each example hash to get parsed to
- [ ] research contracts & figure out which ones you need to interact with, record their addresses
- [ ] record ABIs for any contracts that we need to parse events for
- [ ] implement the parser & get the tests passing
- [ ] implement `getTransactions: (addressBook) => Transactions` function
- [ ] add server endpoint at `/api/transactions/one` that uses above functions to take an address book and syncs data then returns transactions

**Actions**
- [ ] Deposit (move ETH->ONE)
- [ ] Withdraw (move ONE->ETH)
- [ ] Move native asset (ONE) between accounts on Harmony
- [ ] Move tokens between accounts on Harmony
- [ ] Move native asset internally between accounts on Harmony (bonus)
